### PR TITLE
✨Enable branching component

### PR DESCRIPTION
**Pull request by AdrySky**
# Description

This will enable branching workflow by adding `outFlow` port in any node. 

**How it works**
A branch component will have `outFlow` ports. This port will run **first** given condition(if any) its next node until there's no more node. (Let call it branch workflow)
The last node of this workflow can be left hanging or not connecting to any component/node. It doesn't need to end with Finish node(only for branch workflow). 
Then, it'll go back to the branch component to continue with its finished port (▶)(Finished workflow). This workflow **Must** end with `Finish` node.

**How to create a branch node**

1. Use any existing node or create new node.
2. Create a port name(e.g test-branch) as usual but instead of using `InArg` or `OutArg`, use **`BaseComponent`**. This will create an `outFlow` port(test-branch ▶).

> test_branch: BaseComponent

3. Declare in def __init__

> self.test_branch = BaseComponent

4. In def execute

> self.test_branch .do(ctx)

This will make it run the next component of test-branch ▶ port.

**Example of branches component**

There are two example of branches component:
    - TestFlowPort : Branching workflow with condition.
    - AlphabetSwitch : Branching workflow randomly.

**Minor details changes:**

- Indirectly bypass the `checkAllNodesConnected` when there's at least a connection from Start to Finish.
- Disable InPort accepting multiple links.
- Change the error tooltip UI due to blur bug.

## References

Remake of #159.

## Pull Request Type

- [x] Xircuits Core (Jupyterlab Related changes)
- [x] Xircuits Canvas (Custom RD Related changes)
- [x] Xircuits Component Library
- [ ] Testing Automation
- [ ] Documentation
- [ ] Others (Please Specify)

## Type of Change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Tests

1. Try creating an outFlow port.
    1. Follow as mentioned above.
2. Try creating multiple outFlow ports given condition.
    1. You can try creating your own or use the 2 example branch component.
    2. Try running xircuits using it. You can follow the description on how to use it.
3. (Additional) Xircuits can run when there's at least have one complete workflow(Start to Finish).
    1. Try creating a complete workflow.
    3. Add another component. Don't connect the node.
    4. Try running it. It's expected to work.
5. Try compiling workflow without ending with Finish node.
    1. An error tooltip will be display.
6. Try running without connecting one/both `outFlow` port but Finished port (▶) port must be connected.
    1. If either/both port not connected, it will run the Finished port (▶) port.
7. Try running without connecting Finished port (▶) port.
    1. An error tooltip will be display.
8. Try different and crazy but feasible workflow. (Let me know if it doesn't work)

## Tested on?

- [ ] Windows  
- [x] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Notes

Currently, it's not possible to pass variable at the end of branch workflow to the finish workflow

### CODE REVIEW

**Review by MFA-X-AI — COMMENTED** [review]
Alright, thanks for 2nd go with the branch component! We've reworked on the implementation as discussed, and here's some behaviors that I've noticed.

### 1. flow ports can be connected to parameter ports

image

### 2. If the next port after a switch component is `Finish`, it will have an incorrect codegen.

image

```
def main(args):

    ctx = {}
    ctx['args'] = args

    c_1 = AlphabetSwitch()
    c_2 = HelloComponent()


    c_1.next = c_3
    c_1.when_A = SubGraphExecutor(c_2)
    c_2.next = None

    next_component = c_1
    while next_component:
        is_done, next_component = next_component.do(ctx)
```

I believe if the next component is Finish, it should be `c_1.next =  None`

### 3. No warnings if extra flow port isn't linked. 

Simple example as below. 

image

This might be up for discussion - I believe all flow ports should be connected. But it should throw a bubble notification on compile time. Right now it gives `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'nextNode')`.

I think these 3 are good for you to work on first.

**Comment by AdrySky** [comment]
Thanks for the reviewed. Fixed the 3 mentioned issue. The last fix should enable you to run any branch component even though its flow ports are not connected.

**Review by MFA-X-AI — COMMENTED** [review]
Thanks for the update! I can confirm that with the latest changes, things are much more robust. 
image
^I could even make a workflow as crazy as this. 

There is one more thing that we should enable - ideally if a branch component main flow is not connected, it'll still be treated as a normal node.
image
Thanks. Hopefully this should be the last change needed.

**Comment by AdrySky** [comment]
Remove node checking from finish port of branching component. Now, it'll treat any branching component same as any 'normal' node.

**Review by MFA-X-AI — APPROVED** [review]
Can confirm it works from the live stream. 😄

**Pull request merged**
