### PR TITLE
✨Add Comment Component

### PR DESCRIPTION
**Pull request by AdrySky**
# Description

This will enable to add comment node for commenting purpose. It can only be added by context menu. It's only scrollable vertically. 

## Pull Request Type

- [ ] Xircuits Core (Jupyterlab Related changes)
- [x] Xircuits Canvas (Custom RD Related changes)
- [ ] Xircuits Component Library
- [ ] Testing Automation
- [ ] Documentation
- [ ] Others (Please Specify)

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tests

1. Add comment node by opening context menu
2. Type any input for comment
3. Edit comment by double-clicking

## Tested on?

- [ ] Windows  
- [x] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Notes

Not sure why I can't resize the textarea. For now, it'll just have vertical scroll.

### CODE REVIEW

**Review by MFA-X-AI — COMMENTED** [review]
Thanks for the PR!
Noticed a lot of changes, it appears we have a state dir now. Probably something to add to the documentation later. The comment box works as expected, but I have a few suggestions for improvement which are hopefully quick fixes:

1. The width of the context menu might need to be enlarged as the `Add Comment` overflows. 
image

2. For this dialog, can you change the text:
Comment: -> Comment Input:
Comment here -> Add your message here.

image

3. For the textbox, can you add a bit of padding between the text and the white outline? Just a few pixels would be good.
image

Other than that, for the next PR it would be great if say the comment box can have a header like components. That way it's more intuitive to drag instead of having to drag on that space between the text box and the comment box.

Great work man. Can't wait to merge it to main.

**Review by mansouralawi — COMMENTED** [review]
Thank you for the PR, It's really helpful to be able to add comment to the canvas.

Reflecting on the issues @MFA-X-AI pointed.

1. comment boc padding and header. looks better now.  
image

2. Comment dialog box
image

3. The context menu still overflows on `Add Comment` , the dynamic width seems not working well. 
image

**Review by MFA-X-AI — COMMENTED** [review]
Awesome work, wasn't expecting the header to be implemented so quick, it feels so much better to drag around now.
image
So 2 things - 
1. The width of the menu is still overflowing
2. If you can rename Comment Box -> Comment:  that would be great.

Thanks!

**Comment by AdrySky** [comment]
Thanks for the review. It's so weird why the context menu not updating. It's working from my side. I think there an issue with the wheel's style. So I just updated that. I hope the issue doesn't persist.

**Comment by mansouralawi** [comment]
Great, work fine. Merging to main.

image

**Pull request merged**
