### PR TITLE
✨ Enable Arg Parsing in Xircuits Entry Point

### PR DESCRIPTION
**Pull request by MFA-X-AI**
# Description

This PR enables passing arguments from the xircuits console entry point. I've applied it so that we can pull `xai_components`, `examples` and `datasets` from branches. 

The two things you can do now is:

1. `xircuits --branch branchName` to pull `xai-components`
2. `xircuits-examples --branch branchName` to pull `examples` and `datasets`

from your specified branch name. I've also added error handling for file pulling and invalid branches.

## References

https://github.com/XpressAI/xircuits/pull/131 https://github.com/XpressAI/xircuits/pull/132

## Pull Request Type

- [x] Xircuits Core (Jupyterlab Related changes)
- [ ] Xircuits Canvas (Custom RD Related changes)
- [ ] Xircuits Component Library
- [ ] Testing Automation
- [ ] Documentation
- [ ] Others (Please Specify)

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Tests

The branch `fahreza/component-submodules` can be used to test differences between master and branch.

**1. Test Entry Point**
1. Download wheel from latest github action
2. Launch xircuits with `xircuits --branch fahreza/component-submodules`, accept to download `xai_components` when prompted
3. Verify that pycaret and modelstash components do not exist
  
**2. Test Example Downloading**
1. Download examples with `xircuits-examples --branch fahreza/component-submodules`
2. Verify that AutoML and MS xircuits examples do not exist

**3. Test Exception Handling**
1. Try  `xircuits --branch` or `xircuits-examples --branch` with an invalid branch name
2. Verify that it returns `examples from XpressAi/Xircuits branch invalidBranch does not exist!`

## Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Notes

1. I've lowercased the `Datasets` directory to match the rest of the repository. 
2. The submodules are treated as `files` instead of `dir` in pygithub and will return a invalid file message. Nonetheless, the rest of the components will be downloaded.

### CODE REVIEW

**Review by mansouralawi — COMMENTED** [review]
Thank you for the PR. 

## Passed tests
- *Download components*
1. `xircuits --branch fahreza/component-submodules` No pycaret or modelstash components **but it launched Xircuits** (expected)

- *Download examples*
1. `xircuits-examples --branch fahreza/component-submodules` No AutoML examples
2. `xircuits-examples --branch invalid_branch_name` returned the error message

## Failed test 
 - *Download components*
 1. `xircuits --branch invalid_branch_name` No error message and launched Xircuits


## Suggested improvement
-  To introduce `xircuits-components` similarly to `xircuits-examples` to download components.  

  
image

**Comment by MFA-X-AI** [comment]
> xircuits --branch invalid_branch_name No error message and launched Xircuits

Oh, for this one you'd need to delete the xai_component folder first since it performs a folder check on start. That does remind me, maybe we can add an entry point just to download the xai_components.

**Comment by mansouralawi** [comment]
When deleting the xai_component folder and running `xircuits --branch invalid_branch_name` it returned the error and then launched Xircuits. (expected)

An additional entry point specific for xai_components download is a good idea.

**Comment by MFA-X-AI** [comment]
Cool. I'll add it to the next "call submodules from entry" PR. :D

**Pull request merged**
