### PR TITLE
Extend Xircuits to include RPA features

### PR DESCRIPTION
**Pull request by yuenherny**
# Description

This PR introduces robotic process automation (RPA) components in Xircuits using the [RPA-Python](https://github.com/tebelorg/RPA-Python) library from Tebel.Automation.

## References

RPA components was listed as one of the wanted features [here](https://github.com/XpressAI/xircuits/projects/1#card-85639295).

## Pull Request Type

- [ ] Xircuits Core (Jupyterlab Related changes)
- [ ] Xircuits Canvas (Custom RD Related changes)
- [x] Xircuits Component Library
- [ ] Xircuits Project Template
- [ ] Testing Automation
- [ ] Documentation
- [ ] Others (Please Specify)

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tests

*Note: Tests are created and added when new RPA components are created.*

**1. Open webpage**

1. Follow the installation instructions [here](https://xircuits.io/docs/Installation), if Xircuits is not installed yet.
2. Launch Xircuits. 
    ```
    $ xircuits
    ```
3. Navigate to *Xircuits Component Library* at the sidebar and make sure *RPA* folder is available and contains necessary components.
4. Navigate to *File Browser* > *examples* and open *RpaOpenWebpage.xircuits*.
5. Compile the `.xircuits` file and execute it.
6. You should see something like the following:
    ```
    Xircuits is running...

    Executing: RpaInit
    Visual automation: False, Chrome: True, Turbo: False
    Bot initiated.

    Executing: RpaUrl
    Opening https://www.xpress.ai/ on browser...
    Browser opened with URL https://www.xpress.ai/.

    Executing: SleepComponent
    Sleeping for 5.0 seconds.

    Executing: RpaClose
    Closing RPA...

    Finish Executing
    ```

## Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [x] Python 3.10.5
- [ ] Others  (State here -> xxx )  

# Notes

NA.

### CODE REVIEW

**Review by MFA-X-AI — COMMENTED** [review]
Thanks for the PR! Sorry for the delay, was tied up with things. Looks super interesting, looking forward to having an RPA library for Xircuits.
That said, I'm having trouble running the example, after tracing the error it seems like it gets stuck on my machine at `r.init()`. Have you experienced this during your run?

**Comment by yuenherny** [comment]
@MFA-X-AI Hi! Thanks for trying out the PR - and sorry for the delayed response. Wondering if you have a screenshot of the error you are getting? If everything works as intended, you should see the below output in the Xircuits output console:
```
Xircuits is running...

Executing: RpaInit
Visual automation: False, Chrome: True, Turbo: False
Bot initiated.

Executing: RpaUrl
Opening https://www.xpress.ai/ on browser...
Browser opened with URL https://www.xpress.ai/.

Executing: SleepComponent
Sleeping for 5.0 seconds.

Executing: RpaClose
Closing RPA...

Finish Executing
```

Which lines were not in the output? That'll help tracing the error.

**Review by MFA-X-AI — CHANGES_REQUESTED** [review]
Apologies for the late reply. There wasn't any output for debugging since it just freezes at init, but we've managed to figure it out after tracing what init() does.  Basically `python-rpa` / `tagui` has some very interesting way of achieving what it does including downloading other things such as PHP and PhantomJS (if you're on windows, it's at your roaming/tagui/src dir) , but the path handling for different os is a bit wonky. Running it in git bash will call `tagui` instead of `tagui.cmd`, which completely halts the operation. The solution is just to run it using cmd or powershell. It does work nicely after. 

So since it does install a lot of additional things outside the usual python packages, I think the best way is to implement it as a submodule, ala pycaret. Do you think you can recreate it as a component library and make PR that adds it as a submodule? 
Here's some resources that might be helpful:
- https://xircuits.io/docs/developer-guide/creating-a-xircuits-component-library
- https://github.com/XpressAI/xai-pycaret

As for the library itself, I think it would it worth it to also have a few other basic rpa building blocks like clicking, double clicking and keyboard input.
These look like low hanging fruits we can try:
- https://github.com/tebelorg/RPA-Python#web-automationspider_web
- https://github.com/tebelorg/RPA-Python#visual-automationsee_no_evil
- https://github.com/tebelorg/RPA-Python#ocr-automation
- https://github.com/tebelorg/RPA-Python#keyboard-automationmusical_keyboard
Let me know if you'd want help for that.

**Review by MFA-X-AI — COMMENTED** [review]
Thanks for the update! Got a few hiccups while trying to retry the examples where the python process just freezes, but managed to get it to work by rebooting and having no chrome windows open. Once a simple run works, it works consistently again. 😄 
One thing I'll update before merging with main is the way the submodule is declared. Currently it's  
`git@github.com:yuenherny/xai-rpa.git` for the url, we'll need to update it to just the `https://github.com/yuenherny/xai-rpa` otherwise other users will get an error log like this
```
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:yuenherny/xai-rpa.git' into submodule path 'C:/Users/Muhammad.Fahreza/Documents/Github/xircuits-rpa-update/xircuits/xai_components/xai_rpa' failed
Failed to clone 'xai_components/xai_rpa'. Retry scheduled
Cloning into 'C:/Users/Muhammad.Fahreza/Documents/Github/xircuits-rpa-update/xircuits/xai_components/xai_rpa'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
I'll apply the fixes directly to this branch.

**Comment by yuenherny** [comment]
Another thing would be removing the redundant submodule declaration from Line 10 to 12 at `.gitmodules`:
```
[submodule "xai-rpa"]
	path = xai-rpa
	url = git@github.com:yuenherny/xai-rpa.git
```
Could you do that while you update the URL? Thanks!

**Comment by MFA-X-AI** [comment]
Since there's the new PR https://github.com/XpressAI/xircuits/pull/203 fixes this, I'll close this one. Thanks!

**Pull request closed without merging**
