### PR TITLE
Transfer learning support with tensorflow keras models and tensorflow datasets

### PR DESCRIPTION
**Pull request by yusufraji**
Welcome to Xircuits! Thank you for making a pull request. Please ensure that your pull request follows the template.

# Description

This introduces three components for easy transfer learning.

- A TFDataset component
- A KerasTransferLearningModel component
- A TrainKerasModel component

## References

N/A, None observed at the moment.

## Pull Request Type

- [ ] Xircuits Core (Jupyterlab Related changes)
- [ ] Xircuits Canvas (Custom RD Related changes)
- [x] Xircuits Component Library
- [ ] Testing Automation
- [ ] Documentation
- [ ] Others (Please Specify)

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tests

I have created a `KerasTransferLearning.xircuits` file to test the components, accompanying this PR. This xircuits file, which can be found in the examples directory also doubles as a tutorial for the introduced components. 

## Tested on?

- [ ] Windows  
- [x] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Notes

Due to the limited computing resources I have, I wasn't able to complete a full epoch training of the .xircuits file, only a few batches.

### CODE REVIEW

**Review by MFA-X-AI — COMMENTED** [review]
Thanks for the PR! TF Keras does have lots of handy modules, glad to get some help on those. 
The TFDataset component is well needed, thanks for adding the implementation.

As per your mention, it appears that the training is indeed very heavy. I've experimented on increasing the batch size to 4 in the model training, even the A100 ran out of memory. Reducing it to 2 made it able to train at 5 mins per epoch, until the EvaluateAccuracy component where it crashed.

Here's a gist for the logs:
https://gist.github.com/MFA-X-AI/66b0366fb3cef8b7543356d5e4fa851d

Considering that, here are a few suggestions / comments:
1. I've noticed that the accuracy drops for the epochs I ran (only 2). Perhaps this workflow actually retrains the whole model. For that, would it be possible to train only the last layer? 
2. Related to 1, perhaps you can refer to a blogpost that does an example of transfer learning using TF Keras. The reason for this is because ideally we'd want new users to be able to try out these examples on the go with reasonable setup.
3. I've noticed the jupyterlab tqdm isn't working well and blots a lot of logs instead of in-line, so I've added ` from .autonotebook import tqdm as notebook_tqdm` which fixes the issue.
4. The component descriptions are very well appreciated! I'll edit it to conform with the format I've made in anther branch.

Thanks. Hit me up here or in discord if you need help.

**Review by MFA-X-AI — CHANGES_REQUESTED** [review]
Alright, this going to the right direction, looks like training an epoch is much lighter now. I can confirm that the workflow completes till the end.

Unfortunately it appears that the current workflow returns rather poor results, it appears to hit a plateau after the first iterations. Here's an output dump:

```
======================================
__   __  ___                _ _
\ \  \ \/ (_)_ __ ___ _   _(_) |_ ___
 \ \  \  /| | '__/ __| | | | | __/ __|
 / /  /  \| | | | (__| |_| | | |_\__ \
/_/  /_/\_\_|_|  \___|\__,_|_|\__|___/

======================================

Xircuits is running...

2022-07-29 17:19:23.380789: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

Executing: TFDataset
/home/fahreza/Github/xircuits-transfer-learning/xircuits/venv/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2022-07-29 17:19:24.887431: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "FAILED_PRECONDITION: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".
2022-07-29 17:19:26.002179: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-29 17:19:26.569011: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38416 MB memory:  -> device: 0, name: A100-PCIE-40GB, pci bus id: 0000:1c:00.0, compute capability: 8.0

Executing: KerasTransferLearningModel
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 input_2 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 mobilenetv2_1.00_224 (Funct  (None, 7, 7, 1280)       2257984   
 ional)                                                          
                                                                 
 global_average_pooling2d (G  (None, 1280)             0         
 lobalAveragePooling2D)                                          
                                                                 
 dense (Dense)               (None, 1000)              1281000   
                                                                 
=================================================================
Total params: 3,538,984
Trainable params: 1,281,000
Non-trainable params: 2,257,984
_________________________________________________________________
None

Executing: KerasModelCompiler

Executing: TrainKerasModel
Epoch 1/10
2022-07-29 17:19:30.832624: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8101
2022-07-29 17:19:31.573509: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: Permission denied
   1/5000 [..............................] - ETA: 6:02:50 - loss: 477528.6250 - mse: 477528.6250 - accuracy: 0.0000e+00 - mae: 688.9990
2022-07-29 17:19:32.514477: I tensorflow/stream_executor/cuda/cuda_blas.cc:1786] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
5000/5000 [==============================] - 157s 31ms/step - loss: 332832.5625 - mse: 332832.5625 - accuracy: 6.0000e-04 - mae: 499.4999
Epoch 2/10
5000/5000 [==============================] - 37s 7ms/step - loss: 332832.5312 - mse: 332832.5312 - accuracy: 7.0000e-04 - mae: 499.4999
Epoch 3/10
5000/5000 [==============================] - 37s 7ms/step - loss: 332832.5312 - mse: 332832.5312 - accuracy: 0.0011 - mae: 499.4999
Epoch 4/10
5000/5000 [==============================] - 38s 8ms/step - loss: 332832.5312 - mse: 332832.5312 - accuracy: 8.0000e-04 - mae: 499.4999
Epoch 5/10
5000/5000 [==============================] - 38s 8ms/step - loss: 332832.5938 - mse: 332832.5938 - accuracy: 9.0000e-04 - mae: 499.4999
Epoch 6/10
5000/5000 [==============================] - 37s 7ms/step - loss: 332832.5312 - mse: 332832.5312 - accuracy: 9.0000e-04 - mae: 499.4999
Epoch 7/10
5000/5000 [==============================] - 39s 8ms/step - loss: 332832.5938 - mse: 332832.5938 - accuracy: 8.0000e-04 - mae: 499.4999
Epoch 8/10
5000/5000 [==============================] - 38s 8ms/step - loss: 332832.5938 - mse: 332832.5938 - accuracy: 8.0000e-04 - mae: 499.4999
Epoch 9/10
5000/5000 [==============================] - 38s 8ms/step - loss: 332832.5938 - mse: 332832.5938 - accuracy: 5.0000e-04 - mae: 499.4999
Epoch 10/10
5000/5000 [==============================] - 38s 8ms/step - loss: 332832.5938 - mse: 332832.5938 - accuracy: 7.0000e-04 - mae: 499.4999

Executing: TFDSEvaluateAccuracy
{'loss': 332832.59375, 'mse': 332832.59375, 'accuracy': 0.000699999975040555, 'mae': 499.49993896484375}

Finish Executing
```
You'd also want to allow users to save the model for future predictions.

As this will be included in the official workflow lineups, I'll have to be more strict in terms of the usability. Hope you can work it out, thanks for the work!

**Comment by yusufraji** [comment]
> 

Thank you for the review. It surely helped catch some of the things I missed earlier. I have improved things and resolved the issue with the poor result. I am working on making further improvements on this.

**Review by MFA-X-AI — APPROVED** [review]
I've noticed that you've accidently added the tf-datasets package to the pytorch requirements.txt, I've taken the liberty to fix that. I've also removed the requirements-full.txt since it's now dynamically fetched.

Other than that - looks like it ran successfully with a much improved accuracy, great job!
Here's a gist:
https://gist.github.com/MFA-X-AI/2b6cb6a94570af20a26ea42dcea31cf6
I've noticed that my suggestion add `from .autonotebook import tqdm as notebook_tqdm` didn't work well. Optionally we could add ipywidgets into the requirements, but since it's just a minor visual inconvenience and so users wouldn't have a bloated venv, I'll let it be.
Thanks for the PR, will merge it in the morning.

**Comment by yusufraji** [comment]
> I've noticed that you've accidently added the tf-datasets package to the pytorch requirements.txt, I've taken the liberty to fix that. I've also removed the requirements-full.txt since it's now dynamically fetched.
> 
> Other than that - looks like it ran successfully with a much improved accuracy, great job! Here's a gist: https://gist.github.com/MFA-X-AI/2b6cb6a94570af20a26ea42dcea31cf6 I've noticed that my suggestion add `from .autonotebook import tqdm as notebook_tqdm` didn't work well. Optionally we could add ipywidgets into the requirements, but since it's just a minor visual inconvenience and so users wouldn't have a bloated venv, I'll let it be. Thanks for the PR, will merge it in the morning.

Owh, my bad with the requirements mix-up. And thanks for the review and fixes. Your idea of reducing visual cletter is right, will get updates on whatever works best from you in the future. It will be great to use whatever works best in the future components, to ensure better compliance with the review process.

**Pull request merged**
