### PR TITLE
✏️ typo fix for pycaret component library

### PR DESCRIPTION
**Pull request by annabelle1217**
Welcome to Xircuits! Thank you for making a pull request. Please ensure that your pull request follows the template.

# Description

Fix typo in `xai_pytorch/training.py` PrepareUnetDataLoader component

## References

None

## Pull Request Type

- [ ] Xircuits Core (Jupyterlab Related changes)
- [ ] Xircuits Canvas (Custom RD Related changes)
- [x] Xircuits Component Library
- [ ] Testing Automation
- [ ] Documentation
- [ ] Others (Please Specify)

## Type of Change

- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tests

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

**1. Test A**

    1. Reload node on Xircuits
    2. Save and compile
    3. Run

## Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Notes

Add if any.

### CODE REVIEW

**Comment by annabelle1217** [comment]
Change highlighted "train" in image below to "test"
image

**Comment by yusufraji** [comment]
Thanks for finding that. Let's ship it. :rocket:  

Is it possible to rename of `tests` to `test` as well? Like in `tests_set`, `tests_loader` e.t.c. What do you think about that @MFA-X-AI ?

**Comment by annabelle1217** [comment]
Great, will change the "tests" to "test" in these two files 
xircuits\xai_components\xai_pytorch\training.py
xircuits\examples\PyTorchUnetTrainSample.xircuits

**Comment by annabelle1217** [comment]
Tested UnetTrain example with changed component, it runs well

**Review by MFA-X-AI — APPROVED** [review]
Looks good. Thanks for contributing to Xircuits. 😁

**Comment by annabelle1217** [comment]
I found that my dataset used for testing still linger around in the Xircuit file, will remove it in another commit

**Pull request merged**
