### PR TITLE
✨ Xircuits Entry Handler for Components + Submodule Components Download

### PR DESCRIPTION
**Pull request by MFA-X-AI**
# Description

This PR introduces more console commands which focuses on downloading component libraries. While dev users using the cloned repo can use `git submodule init` and `git submodule update` to pull the xai_components, users downloading from pip will not be able to as it is no longer a git repository. 

This PR introduces the `xircuits-components` command that allows users to download them.

## References

If applicable, note issue numbers this pull request addresses. You can also note any other pull requests that address this issue and how this pull request is different.

## Pull Request Type

- [x] Xircuits Core (Jupyterlab Related changes)
- [ ] Xircuits Canvas (Custom RD Related changes)
- [x] Xircuits Component Library
- [ ] Testing Automation
- [ ] Documentation
- [ ] Others (Please Specify)

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Tests

**1. Check normal Xircuits component command**

1. Install the wheel from the github action
2. run `xircuits-components`. Verify that `xai_components` have been downloaded.
    
**2. Check Xircuits component command from a specific branch**

1. Delete previous xai_components directory
2. run `xircuits-components --branch branchName`. Verify that the `xai_components` of that branch have been downloaded. For this you may try branch ``xai_object_classification`. The object_classification components should be there.

**3. Check Xircuits submodule component command from a submodule**
1. Delete previous xai_components directory
2. run `xircuits-components --sublib componentLibraryName`. For this example I will mostly use [xai_pycaret]( https://github.com/XpressAI/xai-pycaret). Verify that:
   1. You can download the component library by using either  `xircuits-components --sublib xai_pycaret` or ` xircuits-components --sublib pycaret`
   2. Using the `--sublib` tag when multiple libraries have the same name will return the first instance (try `--sublib xai`)
   3. Supplying a lib that does not exist will return an error message `component library submodule not found.`
   4. You can chain multiple libraries. `xircuits-components --sublib pycaret modelstash`

**4. Check Xircuits Init**
Check any of the previous `xircuits` console commands, like `xircuits-examples`. It will always print the message and init .xircuits.

## Tested on?

- [ ] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Notes

1. With the current method, users clone from master instead of the specific submodule commit.
2. I've also added 3 ADRs with this PR on the context, refactor component libraries as submodules, as well as submodule libraries and templates.

### CODE REVIEW

**Review by mansouralawi — CHANGES_REQUESTED** [review]
Thank you for the PR, this feature will be very useful for Xircuits built using the wheel. 

Test:

>1. Check normal Xircuits component command

`Test Passed`

> 2. Check Xircuits component command from a specific branch

`Test Failed`

Ran command `xircuits-components --branch xai_object_classification`

output:
image

image

>3. Check Xircuits submodule component command from a submodule 
> i. run xircuits-components --sublib componentLibraryName. For this example I will mostly use [xai_pycaret](https://github.com/XpressAI/xai-pycaret). Verify that:
You can download the component library by using either xircuits-components --sublib xai_pycaret or --sublib pycaret

`Test Passed`

>ii. Using the `--sublib` tag when multiple libraries have the same name will return the first instance (try `--sublib xai`)

`Test Passed`
- It would be nice to print out the multiple libraries found and the downloaded first instance. 

> iii. Supplying a lib that does not exist will return an error message component library submodule not found.

`Test Passed`

> iv. You can chain multiple libraries. `xircuits-components --sublib pycaret modelstash`

`Test Passed`

>4. Check Xircuits Init, testing `xircuits-examples`

`Test Passed`

- Recommended test after the fixes: Run the same testing process using a user without access to the private repo.

**Comment by MFA-X-AI** [comment]
Thanks for the review, 

> Ran command xircuits-components --branch xai_object_classification

should be fixed now.

> Run the same testing process using a user without access to the private repo.
I was actually planning to do this in this PR, however as I also want to implement a semi-persistent way of allowing users to store their access token securely, it'll be a new feature by itself.

**Review by mansouralawi — COMMENTED** [review]
Thanks for the changes.

All technical tests passed successfully.

It will be nice to implement these:
- Progress bar for component library download.  
- Print out the multiple libraries found and the downloaded first instance.   https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by MFA-X-AI** [comment]
Awesome. For these last 2:
> Progress bar for component library download.
> Print out the multiple libraries found and the downloaded first instance.
Added in https://github.com/XpressAI/xircuits/pull/152/commits/85b4cae0eb39594f8452171d816e28def0682373 and https://github.com/XpressAI/xircuits/pull/152/commits/eb83dffc0335a5af86874d9fdaf7bc9fdf2d38a4
The progress bar isn't perfect since it's printing in-line, but it does serve the purpose of displaying progress in real time.

**Review by mansouralawi — APPROVED** [review]
Thanks for the extra features. both work fine.

**Pull request merged**
