### PR TITLE
✨Allow multiple link for port with string, list and dict type

### PR DESCRIPTION
**Pull request by AdrySky**
# Description

This enable connecting multiple link into port with `string`, `list` and `dict` type which in the codegen side, append the extra values.

## Pull Request Type

- [ ] Xircuits Core (Jupyterlab Related changes)
- [ ] Xircuits Canvas (Custom RD Related changes)
- [ ] Xircuits Component Library
- [ ] Testing Automation
- [ ] Documentation
- [x] Others (Code generator script)

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tests

1. Change any input port into `string` type.
   1. Try connecting 2 literal `string`.
   2. Print output.
   3. Repeat step(i) with literal `list` and `dict`.

## Tested on?

- [ ] Windows  
- [x] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Notes
The original PR focused on enabling multiports for the `any` type, but as discussed, the intended use case implementation via multiports could not be implemented in this PR.

### CODE REVIEW

**Review by MFA-X-AI — CHANGES_REQUESTED** [review]
Thanks for the PR!
I'm getting some issues in the codegen side of things, literal nodes are sometimes returning undefined values. Here's the gist for KerasTrainImageClassifier. 
https://gist.github.com/MFA-X-AI/9be15e0abafb7003371905adb3c7ed28
To reproduce, simply run the codeegn.

I'm investigating further what causes it.

**Comment by AdrySky** [comment]
Sorry. I forgot to put value for default type.

**Comment by mansouralawi** [comment]
Thanks for the fixes.

- Literal nodes are sometimes returning undefined values: `issue is fixed`
- Append list,dict,str when input node is [any] type `working fine`

##issue
1- Append list,dict,str when the input node is [list,dict or str] type `not working`
2- Appending literals although they belong to different input nodes. to reproduce try `AutoMLClassificationBlendModels.xircuits`

multi_error

**Comment by AdrySky** [comment]
Thanks @mansouralawi for the review. Both issue fixed on my side. Appreciate if you could review again.

**Review by mansouralawi — CHANGES_REQUESTED** [review]
Thanks for the fixes.

- Literal nodes are sometimes returning undefined values: `issue is fixed`
- Append list,dict,str when input node is [any] type `working fine`
- Append list,dict,str when the input node is [list,dict or str] type `working fine`
- Appending literals although they belong to different input nodes. 'issue is fixed'

## Issue
1- Appending 2 trained models of type [any] to input node type [any] produce the error below.  (The target is to append the two models to a list)

image
outarg_error

**Review by MFA-X-AI — APPROVED** [review]
As discussed, the `any` implementation requires additional features to be added, but for `string` `list` and `dict` it's perfect. Tested and working.
 One interesting to note was the order of the append - it follows the order of when the link was created. In the future it would be cool to indicate the order, perhaps by link label.

**Pull request merged**
