### PR TITLE
✨Add branch component

### PR DESCRIPTION
**Pull request by AdrySky**
# Description

This will add a branch component to enable branching of the workflow. This also indirectly bypass the `checkAllNodesConnected` when there's at least a connection from `Start` to `Finish`. Last node from both `If` port can be any node except **Finish node**. **Finish node** must only be connected from `Finished ▶` port. `Finished ▶` port of branch component **MUST** be connected. 

This also fix `hyperparameter boolean` doesn't give correct value.

Branch component have one `inPort` and two `outPorts`:

**`inPort`**

1. condition (`bool`) : Can be left empty. Default = True. 

**`outPorts`**

1. `If True  ▶` : Can be left empty. If no condition is set and is connected, this will run. 
2. `If False ▶` : Can be left empty. 
3. `Finished ▶` : This will always run. **Must** connect with a node.

Branch with finished Workflow

## Pull Request Type

- [ ] Xircuits Core (Jupyterlab Related changes)
- [x] Xircuits Canvas (Custom RD Related changes)
- [x] Xircuits Component Library
- [ ] Testing Automation
- [ ] Documentation
- [x] Others (Python code generator)

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tests

1. Try create a workflow using a branch component.
   1. Try using literal node to set the `condition`.
2. Try creating multiple workflow using multiple branch component.
   1. Try using hyperparameter node to set the `condition`.
3. (Additional) Xircuits can run when there's at least have one complete workflow(Start to Finish).
   1. Try creating a complete workflow.
   2. Add another component. Don't connect the node.
   3. Try running it. It's expected to work.
4. Try compiling workflow without ending with Finish node.
   1. An error tooltip will be display. 
5. Try running without connecting one/both `If` port but `Finished ▶` port **must** be connected.
   1. If either/both port not connected, it will run the `Finished ▶` port.
6. Try running without connecting `Finished ▶` port.
   1. An error tooltip will be display. 
7. Try different and crazy but feasible workflow. (Let me know if it doesn't work)

## Tested on?

- [ ] Windows  
- [x] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  ( )  

# Notes

It's inside `Custom` Folder. Also, not sure why but in some area(right side) on canvas, the branch node get distorted. 
There can be only one **Finish** node.

### CODE REVIEW

**Review by MFA-X-AI — CHANGES_REQUESTED** [review]
This one is a big changer, will expect some time of review back and forth. 
Here are some of my comments for now:

1. The codegen when used with the branch component, if there's no node connected to the if true or false, it'll assume that the next component (c2 in this case) exists.
image

2. The branch component should give a tooltip if the condition is not provided. As of now it will run the xircuits but will throw out an error. Alternatively we could set a default to true.

And some other observations, but not really important. 
1. The Finish Node became a proper node
image

2. I think the definition of the branch component can be included inside the the General template.

That's it for now, thanks the work!

**Review by mansouralawi — COMMENTED** [review]
Thanks you for the new features. Here some test I ran:

### Test 1
> **`outPorts`** 
> 1. `If True  ▶` : Can be left empty. If no condition is set and is connected, this will run. 
> 2. `If False ▶` : Can be left empty. 
> 3. `Finished ▶` : This will always run. **Must** connect with a node.

&

> 1. Try create a workflow using a branch component.
>>   1. Try using literal node to set the `condition`.

image

- The branch component works as explained above. however, I wonder if the logic of `if true is empty and connected` then run `True` is the expected behavior.   





### Test 2

> 3. (Additional) Xircuits can run when there's at least have one complete workflow(Start to Finish).
>>   1. Try creating a complete workflow.
>>   2. Add another component. Don't connect the node.
>>   3. Try running it. It's expected to work.

image

- Work as expected, very awaited enhancement 


### Test 3

> 4. Try compiling workflow without ending with Finish node.
 >>   1. An error tooltip will be display. 

image

- Worked as explained

### Test 4

> 5. Try running without connecting one/both `If` port but `Finished ▶` port **must** be connected.
>>   1. If either/both port not connected, it will run the `Finished ▶` port. 
> 6. Try running without connecting `Finished ▶` port.
>>   1. An error tooltip will be display. 

- Worked as explained

Issues:

- As Fahreza mentioned `The Finish Node became a proper node`
- Using multibranch components throw tooltip error message to connect components 
image

**Comment by AdrySky** [comment]
Thanks @MFA-X-AI and @mansouralawi for the reviewed. I made some changes like making the `Start` node the same as the other node.

> The branch component should give a tooltip if the condition is not provided. As of now it will run the xircuits but will throw out an error. Alternatively we could set a default to true.

I'm not sure what error you got but it's by default `True`. Even no condition provided, it can still run. 

> The branch component works as explained above. however, I wonder if the logic of `if true is empty and connected` then run True is the expected behavior.

It's by default `True`. Even `If True` empty, it'll run the `Finished` port.

**Review by MFA-X-AI — CHANGES_REQUESTED** [review]
Alright, looks like things are working nicely. I've tried test 1-6, everything looks good. 😄 
Now test 7... "Try different and crazy but feasible workflow. (Let me know if it doesn't work)": I've tried to do this one:

Consider a canvas that looks like this.
image
Where depending on the branch component, it will either use the `mnist` dataset or `mnist-fashion` dataset. Currently the way it is codegen'd will give the following output, where c4_dataset will be overwritten regardless if it was true or false.


```
    c_1 = Branch()
    c_2 = ReadDataSet()
    c_3 = ReadDataSet()
    c_4 = TrainTestSplit()

    c_1.condition.value = False
    c_2.dataset_name.value = """fashion_mnist"""
    c_3.dataset_name.value = """mnist"""
    c_4.dataset = c_3.dataset
    c_4.dataset = c_2.dataset
```

So what I think should do the trick would be giving it an extra tab for if conditions like this:

```
    c_1 = Branch()
    c_2 = ReadDataSet()
    c_3 = ReadDataSet()
    c_4 = TrainTestSplit()

    c_1.condition.value = False
    c_2.dataset_name.value = """fashion_mnist"""
    c_3.dataset_name.value = """mnist"""
   if c_1.condition.value == True:
        c_4.dataset = c_3.dataset
   else if c_1.condition.value==False:
         c_4.dataset = c_2.dataset
   
```
Here's a gist of the xircuits file if you want to give it a try.
https://gist.github.com/MFA-X-AI/402aaf74785f01d90b86fcf3577e26e9

From a codegen perspective you might need to convert the amount of python spaces / tabs into a variable and take count. This would be helpful especially for big nested loops.

It's a big feature, you're almost there. Thanks for the hard work!

**Comment by wmeddie** [comment]
While this almost works, we've decided to rework how branching works.

**Pull request closed without merging**
