### PR TITLE
🐛 Literal Data Validation to Prevent Compilation Breaks

### PR DESCRIPTION
**Pull request by MFA-X-AI**
# Description

This pull request addresses an issue where users can break the compile process by using incorrect input strings, such as not putting quotations around strings in lists. The code changes introduce a type check to prevent this from happening, ensuring a more robust and reliable compilation process.

The type check has been applied in three key areas:

- When a new literal node is created
- When a literal node is edited
- When users create a new literal node from an 'any' type inPort
We encourage users to test these changes and provide feedback for further improvements.

## Pull Request Type

- [x] Xircuits Core (Jupyterlab Related changes)
- [x] Xircuits Canvas (Custom RD Related changes)
- [ ] Xircuits Component Library
- [ ] Xircuits Project Template
- [ ] Testing Automation
- [ ] Documentation
- [ ] Others (Please Specify)

## Type of Change

- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tests

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

**1. Check New Literal**

  1. Create a new literal node with incorrect input strings. IE [testStr] for List, {a:1} for dict.
  2. Verify that the type check prevents the node from being created.

**2. Check Edited Literal**
  1. Edit a literal node with incorrect input strings. IE [testStr] for List, {a:1} for dict.
  2. Verify that the type check prevents the node from being created.

**3. Check Any Type Handing**
  1. Create a literal from an `any` inPort, ie in Component Print.
  2. Verify that the type check prevents the node from being created.

## Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Notes

Add if any.

### CODE REVIEW

**Review by mansouralawi — COMMENTED** [review]
Thanks for the PR. 

The functionalities intended work as expected. It will prevent the user from creating list,dict literals when the keyed-in format is wrong.

However, the error messages are a bit confusing.

image

image

image

Perhaps we just need to instruct the user on how to fix the error.

**Comment by MFA-X-AI** [comment]
Gotcha.
I've added a reminder for not quoting variables like this:
image
As well as returning the compiled input as a message:
image

**Comment by mansouralawi** [comment]
Thanks. 

- In the list reminder could we ask users to `double quote` the variable rather than `quote`  

- Additionally, is the new reminder applied over the `any` port literals? I couldn't reproduce the new reminders there.

image

**Comment by MFA-X-AI** [comment]
Here's the updated error message.
image
Common errors like unquoted variables will be displayed in the alert, for more complex problems users are directed to check the console log.

**Comment by mansouralawi** [comment]
Thanks for the changes. Work as described
image
image

**Pull request merged**
